package com.gnt.service;

import java.util.List;

import com.gnt.mapper.BaseMapper;

public class BaseServiceImpl<K, V> implements BaseService<K, V>{

	BaseMapper<K, V> baseMapper;

	public BaseServiceImpl() {
	}

	public BaseServiceImpl(BaseMapper<K, V> baseMapper) {
		this.baseMapper = baseMapper;
	}
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce
     *
     * @mbg.generated
     */
    public int deleteByPrimaryKey(K k) {
    	return this.baseMapper.deleteByPrimaryKey(k);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce
     *
     * @mbg.generated
     */
    public int insert(V v) {
    	return this.baseMapper.insert(v);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce
     *
     * @mbg.generated
     */
    public int insertSelective(V v) {
    	return this.baseMapper.insertSelective(v);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce
     *
     * @mbg.generated
     */
    public V selectByPrimaryKey(K k) {
    	return this.baseMapper.selectByPrimaryKey(k);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce
     *
     * @mbg.generated
     */
    public int updateByPrimaryKeySelective(V v) {
    	return this.baseMapper.updateByPrimaryKeySelective(v);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce
     *
     * @mbg.generated
     */
    public int updateByPrimaryKey(V v) {
    	return this.baseMapper.updateByPrimaryKey(v);
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce
     *
     * @mbg.generated
     */
    public List<V> selectAll() {
    	return this.baseMapper.selectAll();
    }
}
